### ISSUE TITLE
documentation page is not available

### ISSUE THREAD

**Issue by jrfullstack** [yt-dlx/yt-dlx#1]
Hi, the documentation page is not available, and the crypto package is deprecated
I would like to try your library, 

![image](https://github.com/yt-dlx/yt-dlx/assets/96630703/350e6bec-259e-45a0-93ce-55d402d0b056)

greetings

**Comment by yt-dlx** [comment]
Yes Sir. Please Hang On. The Website is being made and will be available soon. I will inform soon.

**Comment by yt-dlx** [comment]
https://yt-dlx-shovit.koyeb.app/pkg

You can check for the documentation in future

**Comment by yt-dlx** [comment]
![image](https://github.com/yt-dlx/yt-dlx/assets/160623192/21322f53-ebe0-4568-9736-9bbefe4af0c3)


You can check it out now 'https://yt-dlx-shovit.koyeb.app/pkg'
'mixly' is not yet ready but yt-dlx is stable.

NOTE:
'Playlists' related documentations are soon to be added.


> Hi, the documentation page is not available, and the crypto package is deprecated I would like to try your library,
> 
> ![image](https://private-user-images.githubusercontent.com/96630703/310267372-350e6bec-259e-45a0-93ce-55d402d0b056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTYwMjUsIm5iZiI6MTcxMTk1NTcyNSwicGF0aCI6Ii85NjYzMDcwMy8zMTAyNjczNzItMzUwZTZiZWMtMjU5ZS00NWEwLTkzY2UtNTVkNDAyZDBiMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YmVjOWM2NmUyNDE4ZTk4ZjY5N2UzZTZmMTBmMzVmYzYxZWFiMWFmZTRiNTVhNGJlMmZmNmE1YmQ1ODQ0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QLJFyJMSFnMriT6W1yVIfnC5laB_7Z5XWEwN-U6uARQ)
> 
> greetings
