### ISSUE TITLE
Unable to reach Mixly site

### ISSUE THREAD

**Issue by rhydiaan** [yt-dlx/yt-dlx#2]
I'm trying to look at the site for detailed docs in order to use the package in a personal project but I'm unable to reach it.
![image](https://github.com/yt-dlx/yt-dlx/assets/104390718/a7d5b6af-f5fc-49b7-9ebb-e6797f06f862)

**Comment by yt-dlx** [comment]
https://yt-dlx-shovit.koyeb.app/pkg


You can check it out now. 
'mixly' is not yet ready but yt-dlx is stable.

NOTE:
'Playlists' related documentations are soon to be added.

**Comment by yt-dlx** [comment]
> I'm trying to look at the site for detailed docs in order to use the package in a personal project but I'm unable to reach it. ![image](https://private-user-images.githubusercontent.com/104390718/316263107-a7d5b6af-f5fc-49b7-9ebb-e6797f06f862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTYwNjUsIm5iZiI6MTcxMTk1NTc2NSwicGF0aCI6Ii8xMDQzOTA3MTgvMzE2MjYzMTA3LWE3ZDViNmFmLWY1ZmMtNDliNy05ZWJiLWU2Nzk3ZjA2Zjg2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwNzE2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzQ5OTQ3YTZhNDYxZjZmZDNjNjdkYWU0NGY3NDYxMjAzYjFkZjZlMWFkY2IwZWI0NjJhODBmMDViMGI1YzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ycJEza444YCvpK-98lR8IFcsSh1kZ9f61NAId0uaqps)

![image](https://github.com/yt-dlx/yt-dlx/assets/160623192/21322f53-ebe0-4568-9736-9bbefe4af0c3)


You can check it out now 'https://yt-dlx-shovit.koyeb.app/pkg'
'mixly' is not yet ready but yt-dlx is stable.

NOTE:
'Playlists' related documentations are soon to be added.
